export const TODOS = {
    IMMUTABLE_TOGGLE_COMPLETE: 'IMMUTABLE_TOGGLE_COMPLETE',
    IMMUTABLE_CHANGE_FILTER: 'IMMUTABLE_CHANGE_FILTER',
    IMMUTABLE_EDIT_ITEM: 'IMMUTABLE_EDIT_ITEM',
    IMMUTABLE_DONE_EDITING: 'IMMUTABLE_DONE_EDITING',
    IMMUTABLE_CANCEL_EDITING: 'IMMUTABLE_CANCEL_EDITING',
    IMMUTABLE_CLEAR_COMPLETED: 'IMMUTABLE_CLEAR_COMPLETED',
    IMMUTABLE_DELETE_ITEM: 'IMMUTABLE_DELETE_ITEM',
    IMMUTABLE_ADD_ITEM: 'IMMUTABLE_ADD_ITEM',
}