export const TODOS = {
    IMMUTABLE_TOGGLE_COMPLETE: 'IMMUTABLE_TOGGLE_COMPLETE',
    IMMUTABLE_CHANGE_FILTER: 'IMMUTABLE_CHANGE_FILTER',
    IMMUTABLE_CLEAR_COMPLETED: 'IMMUTABLE_CLEAR_COMPLETED',
    IMMUTABLE_DELETE_ITEM: 'IMMUTABLE_DELETE_ITEM',
    IMMUTABLE_ADD_ITEM: 'IMMUTABLE_ADD_ITEM',
}