export const USER = {
    MUTABLE_UPDATE_DEEP: 'MUTABLE_UPDATE_DEEP',
    MUTABLE_SET_NAME: 'MUTABLE_SET_NAME',
    IMMUTABLE_UPDATE_DEEP: 'IMMUTABLE_UPDATE_DEEP',
    IMMUTABLE_SET_NAME: 'IMMUTABLE_SET_NAME',
}