export const USER = {
    VANILLA_UPDATE_DEEP: 'VANILLA_UPDATE_DEEP',
    VANILLA_SET_NAME: 'VANILLA_SET_NAME',
    IMMUTABLE_UPDATE_DEEP: 'IMMUTABLE_UPDATE_DEEP',
    IMMUTABLE_SET_NAME: 'IMMUTABLE_SET_NAME',
}