export const TODOS = {
    TOGGLE_COMPLETE: 'TOGGLE_COMPLETE',
    CHANGE_FILTER: 'CHANGE_FILTER',
    EDIT_ITEM: 'EDIT_ITEM',
    DONE_EDITING: 'DONE_EDITING',
    CANCEL_EDITING: 'CANCEL_EDITING',
    CLEAR_COMPLETED: 'CLEAR_COMPLETED',
    DELETE_ITEM: 'DELETE_ITEM',
    ADD_ITEM: 'ADD_ITEM',
}